#!/bin/bash
DIR="$( dirname -- "${BASH_SOURCE[0]}"; )"
# shellcheck disable=SC2016
IFS=' ' read -r -a guess_scores < <(grep "$1" $DIR/games.md | sed 's/[^`]*`\([^`]*\)`.*/\1/')

IFS=$'\n' read -d '' -r -a guess_scores < <(grep "$1" $DIR/games.md | grep -o ".....=....." && printf '\0')
echo "${#guess_scores[@]}: ${guess_scores[@]}"
$DIR/wordle.py "${guess_scores[@]}"
