#!/bin/bash

# Copy results of a game to clipboard in the form GUESSES => ANSWER

if [ -n "$1" ]; then
    if ! line="$(grep "$1:" games.md)"; then
        echo "Can't find '$1'"
        exit 1
    fi
else
    line="$(tail -1 games.md)"
fi

# shellcheck disable=SC2016
result="$(echo "$line" | sed -E 's/^\* ([0-9]+): `([^`]+)` ([^ ]+) `([^`]+)`$/\2 => \4/')"
echo "$result"

if [ "$(uname)" == "Linux" ]; then
    echo "$result" | wl-copy
elif [ "$(uname)" == "Darwin" ]; then
    echo "$result" | pbcopy
fi
