#!/bin/bash

if [ -n "$1" ]; then
    line="$(grep "$1" games.md)"
else
    line="$(tail -1 games.md)"
fi

# shellcheck disable=SC2016
result="$(echo "$line" | sed -E 's/^.+`([^`]+)`.+`([^`]+)`$/\1 => \2/')"
echo "$result"

if [ "$(uname)" == "Linux" ]; then
    echo "$result" | wl-copy
elif [ "$(uname)" == "Darwin" ]; then
    echo "$result" | pbcopy
fi
